[pytest]
bdd_features_base_dir = test/
env =
  D:TROLIE_BASE_URL=http://localhost:4010
  D:TZ=America/Indiana/Indianapolis
  D:RATINGS_PROVIDER_TOKEN=dummy
  #D:RATE_LIMITING=true

markers =
  forecasting: tests Forecasting core functionality
  realtime: tests Real-time core functionality
  seasonal: tests Seasonal Ratings core functionality
  seasonal_overrides: tests Seasonal Overrides functionality
  temporary_aar_exceptions: tests Temporary AAR Exceptions functionality
  monitoring_sets: tests Monitoring Sets functionality
  skip_rate_limiting: skip rate limiting tests
  requires_model: tests that required loading the test model file
  offset_regional: tests for offset regional limits snapshot filtering
  auth: tests that require authentication

filterwarnings =
    ignore::DeprecationWarning
    ignore:usefixtures.*without arguments has no effect:pytest.PytestWarning
